version: '3.8'

services:

  frontend:
    container_name: lentovaraukset_frontend
    restart: always
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./staging/nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
    container_name: lentovaraukset_backend
    restart: always
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    links:
      - db
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLOUD_INSTANCE=${CLOUD_INSTANCE}
      - TENANT_ID=${TENANT_ID}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - POST_LOGOUT_REDIRECT_URI=${POST_LOGOUT_REDIRECT_URI}
      - EXPRESS_SESSION_SECRET=${EXPRESS_SESSION_SECRET}
      - BASE_PATH=${BASE_PATH}

  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - data:/var/lib/postgresql/data

volumes:
  data:

networks:
  default:
   external:
     name: ohtup